### ISSUE TITLE
Set up Backend Development Server on AWS EC2

### ISSUE THREAD

**Issue by blackchapel** [SimPPL/arbiter-project-tracking#2]
There is a need for the backend to be hosted on a server so that the frontend team can integrate all the APIs easily.

**Comment by blackchapel** [comment]
We used t2.micro AWS EC2 instance to accomplish this task

**Comment by SwapneelM** [comment]
Thank you for the explanation, but could you be a bit more clear as in where are the steps linked to run the server?

Something that would really help (aka please do this) is as follows. You don't have to do this for every issue but once you do it, you can reference it in other issues using the link to that comment:

1. Log into the AWS Console at [some link]
2. Select EC2 from the search bar
3. Select a t2.micro instance from the results
4. When you launch and SSH into the server, create a conda env with X, Y, Z
5. Clone this repo `A` in the folder `B`
6. Run this command `C` to set up a server 
7. Your server should be accessible at <IP Address or how to find the IP address>
8. < next steps >

@blackchapel @Jenil-Savla
