### ISSUE TITLE
AWS Glue Hive Partitioning Do's & Don'ts Documentation

### ISSUE THREAD

**Issue by blackchapel** [SimPPL/arbiter-project-tracking#24]
Link to Wiki Page: https://github.com/SimPPL/arbiter-project-tracking/wiki/Hive-Partitioning

Describe the process, our experience and challenges faced during the hive partitioning process, hence documenting the blockers & green flags learnt along the way.

**Comment by vidhitapai** [comment]
@Jenil-Savla requesting your team's input on the [Hive Partitioning using DuckDB](https://github.com/SimPPL/arbiter-project-tracking/wiki/Hive-Partitioning#using-duckdb) section of the wiki page.
