### ISSUE TITLE
Auto deployment failed

### ISSUE THREAD

**Issue by Jenil-Savla** [SimPPL/arbiter-project-tracking#36]
Looks like the GitHub access keys have expired
![image](https://github.com/SimPPL/arbiter-project-tracking/assets/85385544/c7decc6f-8d85-4853-872f-97fd8c6d007a)

**Comment by blackchapel** [comment]
This has been fixed. The problem was keeping a custom name of the ssh key generated for pulling the code from GitHub to AWS EC2. Even after adding the custom name to the ssh agent, it wasn't reading the key, haven't figured out why. Created a new key with the default name, which fixed the issue
