### ISSUE TITLE
Test the deployment on a t2.small ec2 instance

### ISSUE THREAD

**Issue by Jenil-Savla** [SimPPL/arbiter-project-tracking#38]
As some of the endpoints get interripted on a micro instance due to exhaustion of processing resources and the problem is resolved on a medium instance. 
Setup a t2 small instance to test it's feasibility.

**Comment by blackchapel** [comment]
Better than micro, but not sufficient, still some queries are getting interrupted midway. Either we'll need to use t2.medium or else some of the alternatives that Swapneel suggested.
